[PGY_LOGIN]
id = 1
page_size= 300
cookic= 'a1=19882f48bcap04qq1r777p9ggafrdrroz4abocygo50000339517; webId=e7111fec356dc781ca1d14d236afda9a; customerClientId=016216997022661; abRequestId=e7111fec356dc781ca1d14d236afda9a; x-user-id-creator.xiaohongshu.com=634cc30badd08a00019ee4e3; gid=yjYSKK8dd0uiyjYYJi4YD4SvS0U84AAyFWWW0klUjkk0iD28FfFFll888qqj2yW8DY2KKijK; x-user-id-ad-market.xiaohongshu.com=67bbea69000000000d009ec6; access-token-ad-market.xiaohongshu.com=customer.ad_market.AT-68c517561719769394855947z3wtukxckssgow61; x-user-id-pgy.xiaohongshu.com=634cc30badd08a00019ee4e3; web_session=0400698efe0fc8579efe17fe2f3b4b3c80cddc; customer-sso-sid=68c517578692676989763584p3kokfjxczyqf3qv; solar.beaker.session.id=AT-68c517578692676989779970gcngfg3cgwuaml38; access-token-pgy.xiaohongshu.com=customer.pgy.AT-68c517578692676989779970gcngfg3cgwuaml38; access-token-pgy.beta.xiaohongshu.com=customer.pgy.AT-68c517578692676989779970gcngfg3cgwuaml38; access-token-creator.xiaohongshu.com=customer.creator.AT-68c517578784490505666564igyvep2gywzduakc; galaxy_creator_session_id=wgqyCXYHHZnXyjySugQMxTZRruwpcrshscaG; galaxy.creator.beaker.session.id=1764573271147082968127; webBuild=4.86.0; xsecappid=ratlin; acw_tc=0a0d0e0317645813871915291e153f9451878f63275868a40173047b073bdd; loadts=1764581524768',

[FORM_CONFIG]
# 邀约表单配置
product_name = 小红书合作
product_type_description = 你好，小红书合作，辛苦留个联系方式

[QUERY]
max_account_id = 10000
min_account_id = 1
excluded_ids = 6519
enable_status = 1,2
batch_processing_size = 50

[API_TARGETS]
targets = notes_rate,fans_profile,data_summary,solar/cooperator/user/blogger,fans_overall_new_history,fans_summary,notes_detail

[SCHEDULER]
# 调度器配置
enable_scheduler = True
# 每天执行时间，格式：HH:MM
daily_time = 08:30
# 是否启用单次执行模式（False表示循环调度）
run_once = True
# 调度器检查间隔（秒）
check_interval = 1
