[PGY_LOGIN]
id = 1
page_size= 23

[API_TARGETS]
targets = notes_rate,fans_profile,data_summary,user/blogger,fans_overall_new_history,fans_summary,notes_detail,notes_rate

[SCHEDULER]
# 调度器配置
enable_scheduler = True
# 每天执行时间，格式：HH:MM
daily_time = 19:00
# 是否启用单次执行模式（False表示循环调度）
run_once = True
# 调度器检查间隔（秒）
check_interval = 1

[PGY_USER]
user_id = 1

[API_CONFIG]
employee_name = admin
# API基础URL
;base_url = http://47.117.133.51:30015/api/xiaohongshu-pgy
# API Token（请替换为实际的token）
;token = dasljgirmdxodfdm
token = Dt0BtlTZOnJj1O9X
