from typing import Dict, Any

TABLE_MAPPING: Dict[str, Dict[str, Any]] = {
    'blogger_info': {
        'mysql_table': 'fp_creator',
        'primary_key': 'platform_user_id',
        'sync_key': 'sync_status',
        'batch_size': 100,
        'is_update': True,
        'state': 0,
        'fields': {
            'platform_user_id': 'platform_user_id',
            'name': 'creator_nickname',
            'headPhoto': 'creator_avatar',
            'gender': 'creator_gender',
            'location': 'creator_location',
            'fansNum': 'fans_count',
            'likeCollectCountInfo': 'like_collect_count',
            'businessNoteCount': 'business_note_count',
            'picturePrice': 'picture_price',
            'videoPrice': 'video_price',
            'interMidNum': 'interact_mid_num',
            'currentLevel': 'account_level',
            'contentTags': 'content_field',
            'noteSign': 'mcn_id',
            'redId': 'platform_account_id',
            'videoShowState': 'video_show_state',
            'pictureShowState': 'picture_show_state',
            'creator_intro': 'creator_intro'
        }
    },
    # 博主笔记数据
    'blogger_note_rate': {
        'mysql_table': 'fp_creator_note_rate',
        'primary_key': 'platform_user_id',
        'sync_key': 'sync_status',
        'batch_size': 1,
        'is_update': False,
        'state': 0,
        'fields': {
            'platform_user_id': 'platform_user_id',
            'noteNumber': 'note_number',
            'videoNoteNumber': 'video_note_number',
            'hundredLikePercent': 'hundred_like_percent',
            'thousandLikePercent': 'thousand_like_percent',
            'noteType': 'note_type_result',
            'tradeNames': 'trade_names',
            'impMedian': 'imp_median',
            'impMedianBeyondRate': 'imp_median_beyond_rate',
            'readMedian': 'read_median',
            'readMedianBeyondRate': 'read_median_beyond_rate',
            'interactionMedian': 'interaction_median',
            'interactionRate': 'interaction_rate',
            'interactionBeyondRate': 'interaction_beyond_rate',
            'likeMedian': 'like_median',
            'collectMedian': 'collect_median',
            'commentMedian': 'comment_median',
            'shareMedian': 'share_median',
            'videoFullViewRate': 'video_full_view_rate',
            'videoFullViewBeyondRate': 'video_full_view_beyond_rate',
            'picture3sViewRate': 'picture3s_view_rate',
            'notes': 'notes',
            'pagePercentVo': 'page_percent_vo',
            'longTermCommonNoteVo': 'long_term_common_note_vo',
            'longTermCooperateNoteVo': 'long_term_cooperate_note_vo',
            'mFollowCnt': 'm_follow_cnt',
            'date_type': 'date_type',
            'advertise_switch': 'advertise_switch',
            'business': 'business',
            'note_type': 'note_type',
            'creator_id': 'creator_id',
        }
    },
    # 博主笔记数据
    'data_summary': {
        'mysql_table': 'fp_creator_data_summary',
        'primary_key': 'platform_user_id',
        'sync_key': 'sync_status',
        'batch_size': 2,
        'is_update': False,
        'state': 0,
        'fields': {
            'platform_user_id': 'platform_user_id',
            'dateKey': 'date_key',
            'noteNumber': 'note_number',
            'noteType': 'note_type_result',
            'tradeNames': 'trade_names',
            'readMedian': 'read_median',
            'readMedianBeyondRate': 'read_median_beyond_rate',
            'interactionMedian': 'interaction_median',
            'interactionBeyondRate': 'interaction_beyond_rate',
            'activeDayInLast7': 'active_day_in_last7',
            'isActive': 'is_active',
            'responseRate': 'response_rate',
            'inviteNum': 'invite_num',
            'easyConnect': 'easy_connect',
            'pictureReadCost': 'picture_read_cost',
            'pictureReadBeyondRate': 'picture_read_beyond_rate',
            'videoReadCost': 'video_read_cost',
            'videoReadBeyondRate': 'video_read_beyond_rate',
            'fans30GrowthRate': 'fans30_growth_rate',
            'fans30GrowthBeyondRate': 'fans30_growth_beyond_rate',
            'mEngagementNum': 'm_engagement_num',
            'creator_id': 'creator_id',
            'estimatePictureCpm': 'estimate_picture_cpm',
            'estimateVideoCpm': 'estimate_video_cpm',
            'picReadCost': 'pic_read_cost',
            'videoReadCostV2': 'video_read_cost_v2',
            'estimatePictureEngageCost': 'estimate_picture_engage_cost',
            'estimateVideoEngageCost': 'estimate_video_engage_cost'
        }
    },

    # 博主笔记数据
    'blogger_data_summary': {
        'mysql_table': 'fp_creator_data_summary',
        'primary_key': 'platform_user_id',
        'sync_key': 'sync_status',
        'batch_size': 2,
        'is_update': False,
        'state': 0,
        'fields': {
            'platform_user_id': 'platform_user_id',
            'dateKey': 'date_key',
            'noteNumber': 'note_number',
            'noteType': 'note_type_result',
            'tradeNames': 'trade_names',
            'readMedian': 'read_median',
            'readMedianBeyondRate': 'read_median_beyond_rate',
            'interactionMedian': 'interaction_median',
            'interactionBeyondRate': 'interaction_beyond_rate',
            'activeDayInLast7': 'active_day_in_last7',
            'isActive': 'is_active',
            'responseRate': 'response_rate',
            'inviteNum': 'invite_num',
            'easyConnect': 'easy_connect',
            'pictureReadCost': 'picture_read_cost',
            'pictureReadBeyondRate': 'picture_read_beyond_rate',
            'videoReadCost': 'video_read_cost',
            'videoReadBeyondRate': 'video_read_beyond_rate',
            'fans30GrowthRate': 'fans30_growth_rate',
            'fans30GrowthBeyondRate': 'fans30_growth_beyond_rate',
            'mEngagementNum': 'm_engagement_num',
            'creator_id': 'creator_id',
            'estimatePictureCpm': 'estimate_picture_cpm',
            'estimateVideoCpm': 'estimate_video_cpm',
            'picReadCost': 'pic_read_cost',
            'videoReadCostV2': 'video_read_cost_v2',
            'estimatePictureEngageCost': 'estimate_picture_engage_cost',
            'estimateVideoEngageCost': 'estimate_video_engage_cost'
        }
    },

    'blogger_note_detail': {
        'mysql_table': 'fp_creator_note_detail',
        'primary_key': 'platform_user_id',
        'sync_key': 'sync_status',
        'batch_size': 1,
        'is_update': False,
        'state': 0,
        'fields': {
            'platform_user_id': 'platform_user_id',
            'readNum': 'read_num',
            'likeNum': 'like_num',
            'collectNum': 'collect_num',
            'isAdvertise': 'is_advertise',
            'isVideo': 'is_video',
            'noteId': 'note_id',
            'imgUrl': 'img_url',
            'title': 'note_title',
            'brandName': 'brand_name',
            'date': 'note_date'
        }
    },

    'blogger_fans_summary': {
        'mysql_table': 'fp_creator_fans_summary',
        'primary_key': 'platform_user_id',
        'sync_key': 'sync_status',
        'batch_size': 1,
        'is_update': False,
        'state': 0,
        'fields': {
            'platform_user_id': 'platform_user_id',
            'fansNum': 'fans_num',
            'fansIncreaseNum': 'fans_increase_num',
            'fansGrowthRate': 'fans_growth_rate',
            'fansGrowthBeyondRate': 'fans_growth_beyond_rate',
            'activeFansL28': 'active_fans_l28',
            'activeFansRate': 'active_fans_rate',
            'activeFansBeyondRate': 'active_fans_beyond_rate',
            'engageFansRate': 'engage_fans_rate',
            'engageFansL30': 'engage_fans_l30',
            'engageFansBeyondRate': 'engage_fans_beyond_rate',
            'readFansIn30': 'read_fans_in_30',
            'readFansRate': 'read_fans_rate',
            'readFansBeyondRate': 'read_fans_beyond_rate',
            'payFansUserNum30d': 'pay_fans_user_num_30d',
            'payFansUserRate30d': 'pay_fans_user_rate_30d',
            'creator_id': 'creator_id',
        }
    },

    'blogger_fans_profile': {
        'mysql_table': 'fp_creator_fans_profile',
        'primary_key': 'platform_user_id',
        'sync_key': 'sync_status',
        'batch_size': 1,
        'is_update': False,
        'state': 0,
        'fields': {
            'platform_user_id': 'platform_user_id',
            'ages': 'fans_ages',
            'gender': 'fans_gender',
            'interests': 'fans_interests',
            'provinces': 'fans_provinces',
            'cities': 'fans_cities',
            'devices': 'fans_devices',
            'dateKey': 'date_key',
            'creator_id': 'creator_id',
        }
    },

    'blogger_fans_history': {
        'mysql_table': 'fp_creator_fans_history',
        'primary_key': 'platform_user_id',
        'sync_key': 'sync_status',
        'batch_size': 100,
        'is_update': False,
        'state': 0,
        'fields': {
            'platform_user_id': 'platform_user_id',
            'num': 'fans_num',
            'dateKey': 'date_key',
            'creator_id': 'creator_id',
        }
    },

    'cost_effective': {
        'mysql_table': 'fp_creator_cost_effective',
        'primary_key': 'platform_user_id',
        'sync_key': 'sync_status',
        'batch_size': 1,
        'is_update': False,
        'state': 0,
        'fields': {
            'platform_user_id': 'platform_user_id',
            'date': 'date_key',
            'pictureReadCost': 'picture_read_cost',
            'videoReadCost': 'video_read_cost',
            'pictureSurpassRate': 'picture_surpass_rate',
            'videoSurpassRate': 'video_surpass_rate',
            'pictureCase': 'picture_case',
            'videoCase': 'video_case',
            'estimatePictureCpm': 'estimate_picture_cpm',
            'estimatePictureCpmCompare': 'estimate_picture_cpm_compare',
            'estimateVideoCpm': 'estimate_video_cpm',
            'estimateVideoCpmCompare': 'estimate_video_cpm_compare',
            'estimatePictureEngageCost': 'estimate_picture_engage_cost',
            'estimatePictureEngageCostCompare': 'estimate_picture_engage_cost_compare',
            'estimateVideoEngageCost': 'estimate_video_engage_cost',
            'estimateVideoEngageCostCompare': 'estimate_video_engage_cost_compare',
            'creator_id': 'creator_id',
        }
    },

    'blogger_core_data': {
        'mysql_table': 'fp_creator_core_data',
        'primary_key': 'platform_user_id',
        'sync_key': 'sync_status',
        'batch_size': 100,
        'is_update': False,
        'state': 0,
        'fields': {
            'platform_user_id': 'platform_user_id',
            'dateKey': 'date_key',
            'cpe': 'cpe',
            'cpm': 'cpm',
            'cpv': 'cpv',
            'cpuv': 'cpuv',
            'read': 'read_num',
            'imp': 'imp_num',
            'engage': 'engage_num',
            'thirdUserNum': 'third_user_num',
            'creator_id': 'creator_id',
        }
    },

    'fp_pgy_invitations_info': {
        'mysql_table': 'fp_pgy_invitations_info',
        'primary_key': 'id',
        'sync_key': 'sync_status',
        'batch_size': 100,
        'is_update': True,
        'state': 0,
        'fields': {
            'id': 'id',
            'invitation_details': 'invitation_details',
            'company_remarks': 'company_remarks',
            'recorded_at': 'recorded_at',
            'blogger_name': 'blogger_name',
            'blogger_link': 'blogger_link',
            'blogger_intent': 'blogger_intent',
            'brand_name': 'brand_name',
            'cooperation_type': 'cooperation_type',
            'product_name': 'product_name',
            'expected_publish_period_start': 'expected_publish_period_start',
            'expected_publish_period_end': 'expected_publish_period_end',
            'cooperation_content': 'cooperation_content',
            'contact_information': 'contact_information',
            'invitation_initiation_time': 'invitation_initiation_time',
            'organization': 'organization',
            'clue_type': 'clue_type',
            'platform_user_id': 'platform_user_id',
            'account_source': 'account_source',
            'created_at': 'created_at',
            'is_handle': 'is_handle',
        }
    },

    # 抖音KOL扩展数据 (other_api_data)
    "douyin_kol_profile": {
        "mysql_table": "fp_douyin_kol_profile",
        "primary_key": "platform_user_id",
        "sync_key": "sync_status",
        "batch_size": 2,
        "is_update": False,
        "state": 0,
        "fields": {
            "platform_user_id": "platform_user_id",
            "douyin_sec_uid": "douyin_sec_uid",
            "price_1_20s": "price_1_20s",
            "price_20_60s": "price_20_60s",
            "price_60s_plus": "price_60s_plus",
            "price_platform_raw": "price_platform_raw",
            "expect_cpe": "expect_cpe",
            "expect_cpm": "expect_cpm",
            "platform_hot_rate": "platform_hot_rate",
            "expect_read": "expect_read",
            "search_after_view_count": "search_after_view_count",
            "search_after_view_rate": "search_after_view_rate",
            "a3_increase_count": "a3_increase_count",
            "store_entry_cost": "store_entry_cost",
            "business_play_median": "business_play_median",
            "component_click_volume": "component_click_volume",
            "component_click_rate": "component_click_rate",
            "conversion_cpc": "conversion_cpc",
            "aware_user_count": "aware_user_count",
            "interest_user_cost": "interest_user_cost",
            "like_user_count": "like_user_count",
            "connected_user_count": "connected_user_count",
            "male_fan_ratio": "male_fan_ratio",
            "female_fan_ratio": "female_fan_ratio",
            "old_ratio": "old_ratio",
            "region_distribution": "region_distribution",
            "below_ratio": "below_ratio",
        }
    },

    # 抖音KOL营销统计数据 (yingxiao_api_data)
    "douyin_kol_marketing_stats": {
        "mysql_table": "fp_douyin_kol_marketing_stats",
        "primary_key": "id",
        "sync_key": "sync_status",
        "batch_size": 1,
        "is_update": False,
        "state": 0,
        "fields": {
            "platform_user_id": "platform_user_id",
            "douyin_business": "douyin_business",
            "play_median": "play_median",
            "interaction_volume": "interaction_volume",
            "avg_duration": "avg_duration",
            "completion_rate": "completion_rate",
            "interaction_rate": "interaction_rate",
            "douyin_likes": "douyin_likes",
            "douyin_shares": "douyin_shares",
            "douyin_comments": "douyin_comments",
            "douyin_cpe": "douyin_cpe",
            "douyin_cpc": "douyin_cpc",
        }
    }
}
